name: Build Qt Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest   # Para generar el .exe

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements.txt found"
        pip install pyinstaller PySide6
    - name: Build executable (from Ventana_Principal_TFG)
      working-directory: Ventana_Principal_TFG
      run: |
        pyinstaller main.py --onefile --noconsole --name Launcher_Videojuego `
          --hidden-import PySide6 `
          --hidden-import PySide6.QtCore `
          --hidden-import PySide6.QtGui `
          --hidden-import PySide6.QtWidgets `
          --collect-all PySide6
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Launcher_Videojuego_exe
        path: Ventana_Principal_TFG/dist/Launcher_Videojuego.exe
